name: .NET Deployment

on:
  push:
    tags:
      - '*'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c release -o publish
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Automated Released via GitHub Actions
          files:
            ./tldr/tldr-sharp

